create extension if not exists pgcrypto;

create table if not exists public.canon_entries (
  id uuid primary key default gen_random_uuid(),
  universe_slug text not null,
  series_slug text not null,
  scope text not null check (scope in ('universe', 'series')),
  canonical_key text not null,
  summary text not null check (length(trim(summary)) > 0),
  importance integer not null default 50 check (importance between 1 and 100),
  status text not null default 'canonical' check (status in ('canonical', 'superseded', 'proposed')),
  source_episode_revision text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (universe_slug, series_slug, canonical_key),
  check (
    (scope = 'universe' and series_slug = '__universe__')
    or (scope = 'series' and series_slug <> '__universe__')
  )
);

create table if not exists public.episodes (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'story-factory',
  universe_name text not null,
  universe_slug text not null,
  series_name text not null,
  series_slug text not null,
  episode_no integer not null check (episode_no > 0),
  title text not null,
  premise text not null default '',
  script text not null default '',
  status text not null default 'idea'
    check (status in (
      'idea', 'producing', 'awaiting_approval', 'approved_reserve',
      'scheduled', 'published', 'failed', 'rejected'
    )),
  package jsonb not null default '{}'::jsonb,
  preview_youtube_id text,
  approval_deadline timestamptz,
  approved_revision text,
  rejected_reason text not null default '',
  planned_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (universe_slug, series_slug, episode_no)
);

create table if not exists public.automation_events (
  id bigint generated by default as identity primary key,
  episode_id bigint references public.episodes(id) on delete cascade,
  kind text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists episodes_pipeline_idx
  on public.episodes (status, series_slug, episode_no);
create index if not exists automation_events_lookup_idx
  on public.automation_events (episode_id, kind, created_at desc);

create table if not exists public.episode_memories (
  id uuid primary key default gen_random_uuid(),
  episode_revision text not null unique,
  universe_slug text not null,
  series_slug text not null,
  episode_no integer not null check (episode_no > 0),
  title text not null,
  episode_summary text not null check (length(trim(episode_summary)) > 0),
  memory_delta jsonb not null default '{}'::jsonb,
  status text not null default 'canonical' check (status in ('canonical', 'superseded')),
  committed_at timestamptz not null default now(),
  unique (universe_slug, series_slug, episode_no)
);

create table if not exists public.canon_entry_revisions (
  id uuid primary key default gen_random_uuid(),
  episode_revision text not null,
  universe_slug text not null,
  series_slug text not null,
  scope text not null check (scope in ('universe', 'series')),
  canonical_key text not null,
  summary text not null check (length(trim(summary)) > 0),
  importance integer not null check (importance between 1 and 100),
  status text not null default 'canonical',
  source_episode_revision text not null,
  recorded_at timestamptz not null default now(),
  unique (episode_revision, universe_slug, series_slug, canonical_key)
);

create index if not exists canon_entries_lookup_idx
  on public.canon_entries (universe_slug, series_slug, status, importance desc);
create index if not exists episode_memories_recent_idx
  on public.episode_memories (universe_slug, series_slug, episode_no desc);
create index if not exists canon_entry_revisions_audit_idx
  on public.canon_entry_revisions (universe_slug, series_slug, recorded_at desc);

alter table public.canon_entries enable row level security;
alter table public.episodes enable row level security;
alter table public.automation_events enable row level security;
alter table public.episode_memories enable row level security;
alter table public.canon_entry_revisions enable row level security;

revoke all on table public.canon_entries from anon, authenticated;
revoke all on table public.episodes from anon, authenticated;
revoke all on table public.automation_events from anon, authenticated;
revoke all on table public.episode_memories from anon, authenticated;
revoke all on table public.canon_entry_revisions from anon, authenticated;
grant all on table public.canon_entries to service_role;
grant all on table public.episodes to service_role;
grant all on table public.automation_events to service_role;
grant all on table public.episode_memories to service_role;
grant all on table public.canon_entry_revisions to service_role;
revoke all on all sequences in schema public from anon, authenticated;
grant usage, select on all sequences in schema public to service_role;

comment on table public.canon_entries is
  'Private server-side universe and series canon. No client policies by design.';
comment on table public.episode_memories is
  'Canonical summaries committed only after approval of a master episode.';
comment on table public.canon_entry_revisions is
  'Immutable audit history for every canonical fact written by an approved episode.';
comment on table public.episodes is
  'Supabase control plane for ideas, approvals, scheduling and publication.';
comment on table public.automation_events is
  'Append-only operational log including failures, reminders and metrics.';

create table if not exists public.studio_providers (
  slug text primary key,
  display_name text not null,
  adapter_key text not null,
  enabled boolean not null default false,
  incremental_cost_usd numeric(10,4) not null default 0
    check (incremental_cost_usd >= 0),
  commercial_use_allowed boolean not null default false,
  automation_allowed boolean not null default false,
  watermark_free boolean not null default false,
  supports_dialogue boolean not null default false,
  supports_reference_images boolean not null default false,
  supported_aspect_ratios text[] not null default '{}',
  max_resolution text,
  daily_credit_allowance integer check (daily_credit_allowance is null or daily_credit_allowance >= 0),
  remaining_credits integer check (remaining_credits is null or remaining_credits >= 0),
  credit_cost_per_scene integer not null default 1 check (credit_cost_per_scene > 0),
  next_credit_reset_at timestamptz,
  priority integer not null default 0,
  quality_score numeric(5,2) not null default 0 check (quality_score between 0 and 100),
  success_rate numeric(5,4) not null default 0 check (success_rate between 0 and 1),
  terms_url text not null,
  terms_checked_at timestamptz not null,
  terms_fingerprint text not null,
  secret_names text[] not null default '{}',
  settings jsonb not null default '{}'::jsonb,
  blocked_reason text,
  last_health_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    not enabled
    or (
      incremental_cost_usd = 0
      and commercial_use_allowed
      and automation_allowed
      and watermark_free
      and supports_dialogue
      and supports_reference_images
      and '16:9' = any(supported_aspect_ratios)
      and blocked_reason is null
    )
  )
);

create table if not exists public.scene_jobs (
  id uuid primary key default gen_random_uuid(),
  episode_revision text not null,
  universe_slug text not null,
  series_slug text not null,
  scene_index integer not null check (scene_index >= 0),
  payload jsonb not null,
  status text not null default 'queued'
    check (status in ('queued', 'leased', 'rendering', 'qa', 'retry', 'completed', 'failed')),
  priority integer not null default 0,
  provider_slug text references public.studio_providers(slug),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 3 check (max_attempts between 1 and 10),
  not_before timestamptz not null default now(),
  lease_until timestamptz,
  leased_by text,
  output_url text,
  quality_report jsonb not null default '{}'::jsonb,
  error_log text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (episode_revision, scene_index)
);

create index if not exists studio_provider_router_idx
  on public.studio_providers
  (enabled, incremental_cost_usd, priority desc, quality_score desc);
create index if not exists scene_jobs_queue_idx
  on public.scene_jobs (status, not_before, priority desc, created_at);
create index if not exists scene_jobs_provider_slug_idx
  on public.scene_jobs (provider_slug);

alter table public.studio_providers enable row level security;
alter table public.scene_jobs enable row level security;
revoke all on table public.studio_providers from anon, authenticated;
revoke all on table public.scene_jobs from anon, authenticated;
grant all on table public.studio_providers to service_role;
grant all on table public.scene_jobs to service_role;

create or replace function public.reset_due_studio_credits()
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  changed integer;
begin
  update public.studio_providers
     set remaining_credits = daily_credit_allowance,
         next_credit_reset_at = next_credit_reset_at + interval '1 day',
         updated_at = now()
   where daily_credit_allowance is not null
     and next_credit_reset_at is not null
     and next_credit_reset_at <= now();
  get diagnostics changed = row_count;
  return changed;
end;
$$;

create or replace function public.claim_scene_job(
  worker_name text,
  target_episode_revision text,
  lease_seconds integer default 7200
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  selected_job public.scene_jobs%rowtype;
  selected_provider public.studio_providers%rowtype;
begin
  if worker_name is null or length(trim(worker_name)) < 3 then
    raise exception 'worker_name is required';
  end if;
  if target_episode_revision is null or length(trim(target_episode_revision)) <> 16 then
    raise exception 'target_episode_revision is required';
  end if;
  if lease_seconds < 60 or lease_seconds > 21600 then
    raise exception 'lease_seconds must be between 60 and 21600';
  end if;

  perform public.reset_due_studio_credits();

  select j.*
    into selected_job
    from public.scene_jobs j
   where (
       j.status in ('queued', 'retry')
       or (j.status in ('leased', 'rendering') and j.lease_until < now())
     )
     and j.episode_revision = target_episode_revision
     and j.not_before <= now()
     and j.attempts < j.max_attempts
   order by j.priority desc, j.created_at
   for update skip locked
   limit 1;

  if selected_job.id is null then
    return null;
  end if;

  select p.*
    into selected_provider
    from public.studio_providers p
   where p.enabled
     and p.incremental_cost_usd = 0
     and p.commercial_use_allowed
     and p.automation_allowed
     and p.watermark_free
     and p.supports_dialogue
     and p.supports_reference_images
     and '16:9' = any(p.supported_aspect_ratios)
     and p.blocked_reason is null
     and p.terms_checked_at >= now() - interval '30 days'
     and p.terms_fingerprint not like 'pending%'
     and (
       p.remaining_credits is null
       or p.remaining_credits >= p.credit_cost_per_scene
     )
   order by p.priority desc, p.quality_score desc, p.success_rate desc
   for update skip locked
   limit 1;

  if selected_provider.slug is null then
    return null;
  end if;

  update public.scene_jobs
     set status = 'leased',
         provider_slug = selected_provider.slug,
         attempts = attempts + 1,
         leased_by = worker_name,
         lease_until = now() + make_interval(secs => lease_seconds),
         updated_at = now()
   where id = selected_job.id
   returning * into selected_job;

  if selected_provider.remaining_credits is not null then
    update public.studio_providers
       set remaining_credits = remaining_credits - credit_cost_per_scene,
           updated_at = now()
     where slug = selected_provider.slug;
  end if;

  return jsonb_build_object(
    'job', to_jsonb(selected_job),
    'provider', to_jsonb(selected_provider)
      - 'settings'
      - 'secret_names'
  );
end;
$$;

revoke execute on function public.reset_due_studio_credits() from public, anon, authenticated;
revoke execute on function public.claim_scene_job(text, text, integer) from public, anon, authenticated;
grant execute on function public.reset_due_studio_credits() to service_role;
grant execute on function public.claim_scene_job(text, text, integer) to service_role;

comment on table public.studio_providers is
  'Terms-gated registry. Enabled providers must be zero-incremental-cost, commercial and automation-safe.';
comment on table public.scene_jobs is
  'Durable per-scene production queue consumed by server-side workers only.';

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'story-scenes',
  'story-scenes',
  false,
  524288000,
  array['video/mp4']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into public.studio_providers (
  slug, display_name, adapter_key, enabled, incremental_cost_usd,
  commercial_use_allowed, automation_allowed, watermark_free,
  supports_dialogue, supports_reference_images, supported_aspect_ratios,
  max_resolution, priority, quality_score, success_rate,
  terms_url, terms_checked_at, terms_fingerprint, secret_names, blocked_reason
)
values
  (
    'krea-existing-account', 'Krea – vorhandenes Konto', 'krea_api', false, 0,
    false, false, true, true, true, array['16:9'], '1920x1080',
    100, 85, 0,
    'https://www.krea.ai/terms-of-service', now(), 'pending-verification',
    array['KREA_API_TOKEN'],
    'Kommerzielle Rechte, Automatisierung und enthaltenes API-Kontingent des bestehenden Kontos prüfen'
  ),
  (
    'vidu-free', 'Vidu Free', 'vidu_browser', false, 0,
    false, false, false, true, true, array['16:9'], '1920x1080',
    20, 80, 0,
    'https://www.vidu.com/terms', now(), '2026-07-03',
    '{}',
    'Gratiszugang ist nichtkommerziell; Botting ist laut Nutzungsbedingungen untersagt'
  ),
  (
    'canva-existing-account', 'Canva – vorhandenes Konto', 'canva_browser', false, 0,
    false, false, true, false, true, array['16:9'], '1920x1080',
    50, 65, 0,
    'https://www.canva.com/policies/terms-of-use/', now(), 'pending-verification',
    '{}',
    'Videoerzeugung, kommerzielle Rechte und zulässige Automatisierung des Kontos prüfen'
  )
on conflict (slug) do nothing;
